/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.insights.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.insights.JSON;

/**
 * Identity population and activity counts for the domain, pivoted from the latest tranche the identity metrics provider collected.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class IdentityMetricsDataSet {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_COLLECTED_AT = "collectedAt";
  @SerializedName(SERIALIZED_NAME_COLLECTED_AT)
  private OffsetDateTime collectedAt;

  public static final String SERIALIZED_NAME_PERSONAL_USERS = "personalUsers";
  @SerializedName(SERIALIZED_NAME_PERSONAL_USERS)
  private Long personalUsers;

  public static final String SERIALIZED_NAME_SERVICE_USERS = "serviceUsers";
  @SerializedName(SERIALIZED_NAME_SERVICE_USERS)
  private Long serviceUsers;

  public static final String SERIALIZED_NAME_NEVER_LOGGED_IN = "neverLoggedIn";
  @SerializedName(SERIALIZED_NAME_NEVER_LOGGED_IN)
  private Long neverLoggedIn;

  public static final String SERIALIZED_NAME_IGNORED = "ignored";
  @SerializedName(SERIALIZED_NAME_IGNORED)
  private Long ignored;

  public static final String SERIALIZED_NAME_ACCOUNT_LOCKED = "accountLocked";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_LOCKED)
  private Long accountLocked;

  public static final String SERIALIZED_NAME_SUSPENDED_PW_RESET = "suspendedPwReset";
  @SerializedName(SERIALIZED_NAME_SUSPENDED_PW_RESET)
  private Long suspendedPwReset;

  public static final String SERIALIZED_NAME_CREATED_LAST24_HOURS = "createdLast24Hours";
  @SerializedName(SERIALIZED_NAME_CREATED_LAST24_HOURS)
  private Long createdLast24Hours;

  public static final String SERIALIZED_NAME_CREATED_LAST7_DAYS = "createdLast7Days";
  @SerializedName(SERIALIZED_NAME_CREATED_LAST7_DAYS)
  private Long createdLast7Days;

  public static final String SERIALIZED_NAME_CREATED_LAST30_DAYS = "createdLast30Days";
  @SerializedName(SERIALIZED_NAME_CREATED_LAST30_DAYS)
  private Long createdLast30Days;

  public static final String SERIALIZED_NAME_ACTIVE_LAST24_HOURS = "activeLast24Hours";
  @SerializedName(SERIALIZED_NAME_ACTIVE_LAST24_HOURS)
  private Long activeLast24Hours;

  public static final String SERIALIZED_NAME_ACTIVE_LAST7_DAYS = "activeLast7Days";
  @SerializedName(SERIALIZED_NAME_ACTIVE_LAST7_DAYS)
  private Long activeLast7Days;

  public static final String SERIALIZED_NAME_ACTIVE_LAST30_DAYS = "activeLast30Days";
  @SerializedName(SERIALIZED_NAME_ACTIVE_LAST30_DAYS)
  private Long activeLast30Days;

  public IdentityMetricsDataSet() {
  }

  public IdentityMetricsDataSet name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of this data set. Always &#x60;IdentityMetrics&#x60;, matching the corresponding Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet value and Finbourne.Insights.WebApi.Dtos.Metrics.MetricsResponse property.
   * @return name
  **/
  @jakarta.annotation.Nonnull
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public IdentityMetricsDataSet collectedAt(OffsetDateTime collectedAt) {
    
    this.collectedAt = collectedAt;
    return this;
  }

   /**
   * The timestamp of the tranche these values were collected in, in UTC, or null if no tranche was returned.
   * @return collectedAt
  **/
  @jakarta.annotation.Nullable
  public OffsetDateTime getCollectedAt() {
    return collectedAt;
  }


  public void setCollectedAt(OffsetDateTime collectedAt) {
    this.collectedAt = collectedAt;
  }


  public IdentityMetricsDataSet personalUsers(Long personalUsers) {
    
    this.personalUsers = personalUsers;
    return this;
  }

   /**
   * The number of personal (human) users in the domain, or null if not reported.
   * @return personalUsers
  **/
  @jakarta.annotation.Nullable
  public Long getPersonalUsers() {
    return personalUsers;
  }


  public void setPersonalUsers(Long personalUsers) {
    this.personalUsers = personalUsers;
  }


  public IdentityMetricsDataSet serviceUsers(Long serviceUsers) {
    
    this.serviceUsers = serviceUsers;
    return this;
  }

   /**
   * The number of service users in the domain, or null if not reported.
   * @return serviceUsers
  **/
  @jakarta.annotation.Nullable
  public Long getServiceUsers() {
    return serviceUsers;
  }


  public void setServiceUsers(Long serviceUsers) {
    this.serviceUsers = serviceUsers;
  }


  public IdentityMetricsDataSet neverLoggedIn(Long neverLoggedIn) {
    
    this.neverLoggedIn = neverLoggedIn;
    return this;
  }

   /**
   * The number of users that have never logged in, or null if not reported.
   * @return neverLoggedIn
  **/
  @jakarta.annotation.Nullable
  public Long getNeverLoggedIn() {
    return neverLoggedIn;
  }


  public void setNeverLoggedIn(Long neverLoggedIn) {
    this.neverLoggedIn = neverLoggedIn;
  }


  public IdentityMetricsDataSet ignored(Long ignored) {
    
    this.ignored = ignored;
    return this;
  }

   /**
   * The number of users excluded from the other counts, or null if not reported.
   * @return ignored
  **/
  @jakarta.annotation.Nullable
  public Long getIgnored() {
    return ignored;
  }


  public void setIgnored(Long ignored) {
    this.ignored = ignored;
  }


  public IdentityMetricsDataSet accountLocked(Long accountLocked) {
    
    this.accountLocked = accountLocked;
    return this;
  }

   /**
   * The number of users whose account is locked, or null if not reported.
   * @return accountLocked
  **/
  @jakarta.annotation.Nullable
  public Long getAccountLocked() {
    return accountLocked;
  }


  public void setAccountLocked(Long accountLocked) {
    this.accountLocked = accountLocked;
  }


  public IdentityMetricsDataSet suspendedPwReset(Long suspendedPwReset) {
    
    this.suspendedPwReset = suspendedPwReset;
    return this;
  }

   /**
   * The number of users suspended pending a password reset, or null if not reported.
   * @return suspendedPwReset
  **/
  @jakarta.annotation.Nullable
  public Long getSuspendedPwReset() {
    return suspendedPwReset;
  }


  public void setSuspendedPwReset(Long suspendedPwReset) {
    this.suspendedPwReset = suspendedPwReset;
  }


  public IdentityMetricsDataSet createdLast24Hours(Long createdLast24Hours) {
    
    this.createdLast24Hours = createdLast24Hours;
    return this;
  }

   /**
   * The number of users created in the last 24 hours, or null if not reported.
   * @return createdLast24Hours
  **/
  @jakarta.annotation.Nullable
  public Long getCreatedLast24Hours() {
    return createdLast24Hours;
  }


  public void setCreatedLast24Hours(Long createdLast24Hours) {
    this.createdLast24Hours = createdLast24Hours;
  }


  public IdentityMetricsDataSet createdLast7Days(Long createdLast7Days) {
    
    this.createdLast7Days = createdLast7Days;
    return this;
  }

   /**
   * The number of users created in the last 7 days, or null if not reported.
   * @return createdLast7Days
  **/
  @jakarta.annotation.Nullable
  public Long getCreatedLast7Days() {
    return createdLast7Days;
  }


  public void setCreatedLast7Days(Long createdLast7Days) {
    this.createdLast7Days = createdLast7Days;
  }


  public IdentityMetricsDataSet createdLast30Days(Long createdLast30Days) {
    
    this.createdLast30Days = createdLast30Days;
    return this;
  }

   /**
   * The number of users created in the last 30 days, or null if not reported.
   * @return createdLast30Days
  **/
  @jakarta.annotation.Nullable
  public Long getCreatedLast30Days() {
    return createdLast30Days;
  }


  public void setCreatedLast30Days(Long createdLast30Days) {
    this.createdLast30Days = createdLast30Days;
  }


  public IdentityMetricsDataSet activeLast24Hours(Long activeLast24Hours) {
    
    this.activeLast24Hours = activeLast24Hours;
    return this;
  }

   /**
   * The number of users active in the last 24 hours, or null if not reported.
   * @return activeLast24Hours
  **/
  @jakarta.annotation.Nullable
  public Long getActiveLast24Hours() {
    return activeLast24Hours;
  }


  public void setActiveLast24Hours(Long activeLast24Hours) {
    this.activeLast24Hours = activeLast24Hours;
  }


  public IdentityMetricsDataSet activeLast7Days(Long activeLast7Days) {
    
    this.activeLast7Days = activeLast7Days;
    return this;
  }

   /**
   * The number of users active in the last 7 days, or null if not reported.
   * @return activeLast7Days
  **/
  @jakarta.annotation.Nullable
  public Long getActiveLast7Days() {
    return activeLast7Days;
  }


  public void setActiveLast7Days(Long activeLast7Days) {
    this.activeLast7Days = activeLast7Days;
  }


  public IdentityMetricsDataSet activeLast30Days(Long activeLast30Days) {
    
    this.activeLast30Days = activeLast30Days;
    return this;
  }

   /**
   * The number of users active in the last 30 days, or null if not reported.
   * @return activeLast30Days
  **/
  @jakarta.annotation.Nullable
  public Long getActiveLast30Days() {
    return activeLast30Days;
  }


  public void setActiveLast30Days(Long activeLast30Days) {
    this.activeLast30Days = activeLast30Days;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentityMetricsDataSet identityMetricsDataSet = (IdentityMetricsDataSet) o;
    return Objects.equals(this.name, identityMetricsDataSet.name) &&
        Objects.equals(this.collectedAt, identityMetricsDataSet.collectedAt) &&
        Objects.equals(this.personalUsers, identityMetricsDataSet.personalUsers) &&
        Objects.equals(this.serviceUsers, identityMetricsDataSet.serviceUsers) &&
        Objects.equals(this.neverLoggedIn, identityMetricsDataSet.neverLoggedIn) &&
        Objects.equals(this.ignored, identityMetricsDataSet.ignored) &&
        Objects.equals(this.accountLocked, identityMetricsDataSet.accountLocked) &&
        Objects.equals(this.suspendedPwReset, identityMetricsDataSet.suspendedPwReset) &&
        Objects.equals(this.createdLast24Hours, identityMetricsDataSet.createdLast24Hours) &&
        Objects.equals(this.createdLast7Days, identityMetricsDataSet.createdLast7Days) &&
        Objects.equals(this.createdLast30Days, identityMetricsDataSet.createdLast30Days) &&
        Objects.equals(this.activeLast24Hours, identityMetricsDataSet.activeLast24Hours) &&
        Objects.equals(this.activeLast7Days, identityMetricsDataSet.activeLast7Days) &&
        Objects.equals(this.activeLast30Days, identityMetricsDataSet.activeLast30Days);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, collectedAt, personalUsers, serviceUsers, neverLoggedIn, ignored, accountLocked, suspendedPwReset, createdLast24Hours, createdLast7Days, createdLast30Days, activeLast24Hours, activeLast7Days, activeLast30Days);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentityMetricsDataSet {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    collectedAt: ").append(toIndentedString(collectedAt)).append("\n");
    sb.append("    personalUsers: ").append(toIndentedString(personalUsers)).append("\n");
    sb.append("    serviceUsers: ").append(toIndentedString(serviceUsers)).append("\n");
    sb.append("    neverLoggedIn: ").append(toIndentedString(neverLoggedIn)).append("\n");
    sb.append("    ignored: ").append(toIndentedString(ignored)).append("\n");
    sb.append("    accountLocked: ").append(toIndentedString(accountLocked)).append("\n");
    sb.append("    suspendedPwReset: ").append(toIndentedString(suspendedPwReset)).append("\n");
    sb.append("    createdLast24Hours: ").append(toIndentedString(createdLast24Hours)).append("\n");
    sb.append("    createdLast7Days: ").append(toIndentedString(createdLast7Days)).append("\n");
    sb.append("    createdLast30Days: ").append(toIndentedString(createdLast30Days)).append("\n");
    sb.append("    activeLast24Hours: ").append(toIndentedString(activeLast24Hours)).append("\n");
    sb.append("    activeLast7Days: ").append(toIndentedString(activeLast7Days)).append("\n");
    sb.append("    activeLast30Days: ").append(toIndentedString(activeLast30Days)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("collectedAt");
    openapiFields.add("personalUsers");
    openapiFields.add("serviceUsers");
    openapiFields.add("neverLoggedIn");
    openapiFields.add("ignored");
    openapiFields.add("accountLocked");
    openapiFields.add("suspendedPwReset");
    openapiFields.add("createdLast24Hours");
    openapiFields.add("createdLast7Days");
    openapiFields.add("createdLast30Days");
    openapiFields.add("activeLast24Hours");
    openapiFields.add("activeLast7Days");
    openapiFields.add("activeLast30Days");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to IdentityMetricsDataSet
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IdentityMetricsDataSet.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IdentityMetricsDataSet is not found in the empty JSON string", IdentityMetricsDataSet.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : IdentityMetricsDataSet.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IdentityMetricsDataSet.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IdentityMetricsDataSet' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IdentityMetricsDataSet> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IdentityMetricsDataSet.class));

       return (TypeAdapter<T>) new TypeAdapter<IdentityMetricsDataSet>() {
           @Override
           public void write(JsonWriter out, IdentityMetricsDataSet value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IdentityMetricsDataSet read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of IdentityMetricsDataSet given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of IdentityMetricsDataSet
  * @throws IOException if the JSON string is invalid with respect to IdentityMetricsDataSet
  */
  public static IdentityMetricsDataSet fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IdentityMetricsDataSet.class);
  }

 /**
  * Convert an instance of IdentityMetricsDataSet to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
