/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.insights.model;

import java.util.Objects;
import com.finbourne.insights.model.BooleanComparator;
import com.finbourne.insights.model.DateComparator;
import com.finbourne.insights.model.NumericComparator;
import com.finbourne.insights.model.TextComparator;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.insights.JSON;

/**
 * A single filter applied to a queryable log field. Exactly one comparator (Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Text, Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Numeric, Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Date or Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Boolean) must be populated, and its type must match the data type of the field named by Finbourne.Insights.WebApi.Dtos.Querying.InsightsFilter.Field. The available comparator and operation for a field can be discovered via the queryable-fields metadata endpoint.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class InsightsFilter {
  public static final String SERIALIZED_NAME_FIELD = "field";
  @SerializedName(SERIALIZED_NAME_FIELD)
  private String field;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  private TextComparator text;

  public static final String SERIALIZED_NAME_NUMERIC = "numeric";
  @SerializedName(SERIALIZED_NAME_NUMERIC)
  private NumericComparator numeric;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private DateComparator date;

  public static final String SERIALIZED_NAME_BOOLEAN = "boolean";
  @SerializedName(SERIALIZED_NAME_BOOLEAN)
  private BooleanComparator _boolean;

  public InsightsFilter() {
  }

  public InsightsFilter field(String field) {
    
    this.field = field;
    return this;
  }

   /**
   * The name of the field to filter on (case-insensitive). Must be a filterable field of the queried log type.
   * @return field
  **/
  @jakarta.annotation.Nonnull
  public String getField() {
    return field;
  }


  public void setField(String field) {
    this.field = field;
  }


  public InsightsFilter text(TextComparator text) {
    
    this.text = text;
    return this;
  }

   /**
   * Get text
   * @return text
  **/
  @jakarta.annotation.Nullable
  public TextComparator getText() {
    return text;
  }


  public void setText(TextComparator text) {
    this.text = text;
  }


  public InsightsFilter numeric(NumericComparator numeric) {
    
    this.numeric = numeric;
    return this;
  }

   /**
   * Get numeric
   * @return numeric
  **/
  @jakarta.annotation.Nullable
  public NumericComparator getNumeric() {
    return numeric;
  }


  public void setNumeric(NumericComparator numeric) {
    this.numeric = numeric;
  }


  public InsightsFilter date(DateComparator date) {
    
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @jakarta.annotation.Nullable
  public DateComparator getDate() {
    return date;
  }


  public void setDate(DateComparator date) {
    this.date = date;
  }


  public InsightsFilter _boolean(BooleanComparator _boolean) {
    
    this._boolean = _boolean;
    return this;
  }

   /**
   * Get _boolean
   * @return _boolean
  **/
  @jakarta.annotation.Nullable
  public BooleanComparator getBoolean() {
    return _boolean;
  }


  public void setBoolean(BooleanComparator _boolean) {
    this._boolean = _boolean;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InsightsFilter insightsFilter = (InsightsFilter) o;
    return Objects.equals(this.field, insightsFilter.field) &&
        Objects.equals(this.text, insightsFilter.text) &&
        Objects.equals(this.numeric, insightsFilter.numeric) &&
        Objects.equals(this.date, insightsFilter.date) &&
        Objects.equals(this._boolean, insightsFilter._boolean);
  }

  @Override
  public int hashCode() {
    return Objects.hash(field, text, numeric, date, _boolean);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InsightsFilter {\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    numeric: ").append(toIndentedString(numeric)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    _boolean: ").append(toIndentedString(_boolean)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("field");
    openapiFields.add("text");
    openapiFields.add("numeric");
    openapiFields.add("date");
    openapiFields.add("boolean");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("field");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to InsightsFilter
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!InsightsFilter.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InsightsFilter is not found in the empty JSON string", InsightsFilter.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : InsightsFilter.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("field").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `field` to be a primitive type in the JSON string but got `%s`", jsonObj.get("field").toString()));
      }
      // validate the optional field `text`
      if (jsonObj.get("text") != null && !jsonObj.get("text").isJsonNull()) {
        TextComparator.validateJsonElement(jsonObj.get("text"));
      }
      // validate the optional field `numeric`
      if (jsonObj.get("numeric") != null && !jsonObj.get("numeric").isJsonNull()) {
        NumericComparator.validateJsonElement(jsonObj.get("numeric"));
      }
      // validate the optional field `date`
      if (jsonObj.get("date") != null && !jsonObj.get("date").isJsonNull()) {
        DateComparator.validateJsonElement(jsonObj.get("date"));
      }
      // validate the optional field `boolean`
      if (jsonObj.get("boolean") != null && !jsonObj.get("boolean").isJsonNull()) {
        BooleanComparator.validateJsonElement(jsonObj.get("boolean"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InsightsFilter.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InsightsFilter' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InsightsFilter> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InsightsFilter.class));

       return (TypeAdapter<T>) new TypeAdapter<InsightsFilter>() {
           @Override
           public void write(JsonWriter out, InsightsFilter value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InsightsFilter read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InsightsFilter given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InsightsFilter
  * @throws IOException if the JSON string is invalid with respect to InsightsFilter
  */
  public static InsightsFilter fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InsightsFilter.class);
  }

 /**
  * Convert an instance of InsightsFilter to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
