/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.insights.model;

import java.util.Objects;
import com.finbourne.insights.model.RelativeOffset;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.insights.JSON;

/**
 * One end of a relative time range. Exactly one of the options must be set: Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Now (the current instant), Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Midnight (the start of the current day in the range&#39;s time zone), Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Offset (a duration back from now) or Finbourne.Insights.WebApi.Dtos.Querying.RelativeBoundary.Absolute (an explicit instant).
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RelativeBoundary {
  public static final String SERIALIZED_NAME_NOW = "now";
  @SerializedName(SERIALIZED_NAME_NOW)
  private Boolean now;

  public static final String SERIALIZED_NAME_MIDNIGHT = "midnight";
  @SerializedName(SERIALIZED_NAME_MIDNIGHT)
  private Boolean midnight;

  public static final String SERIALIZED_NAME_OFFSET = "offset";
  @SerializedName(SERIALIZED_NAME_OFFSET)
  private RelativeOffset offset;

  public static final String SERIALIZED_NAME_ABSOLUTE = "absolute";
  @SerializedName(SERIALIZED_NAME_ABSOLUTE)
  private OffsetDateTime absolute;

  public RelativeBoundary() {
  }

  public RelativeBoundary now(Boolean now) {
    
    this.now = now;
    return this;
  }

   /**
   * When &#x60;true&#x60;, this boundary is the current instant (\&quot;now\&quot;).
   * @return now
  **/
  @jakarta.annotation.Nullable
  public Boolean getNow() {
    return now;
  }


  public void setNow(Boolean now) {
    this.now = now;
  }


  public RelativeBoundary midnight(Boolean midnight) {
    
    this.midnight = midnight;
    return this;
  }

   /**
   * When &#x60;true&#x60;, this boundary is the start of the current day (midnight) in the range&#39;s time zone.
   * @return midnight
  **/
  @jakarta.annotation.Nullable
  public Boolean getMidnight() {
    return midnight;
  }


  public void setMidnight(Boolean midnight) {
    this.midnight = midnight;
  }


  public RelativeBoundary offset(RelativeOffset offset) {
    
    this.offset = offset;
    return this;
  }

   /**
   * Get offset
   * @return offset
  **/
  @jakarta.annotation.Nullable
  public RelativeOffset getOffset() {
    return offset;
  }


  public void setOffset(RelativeOffset offset) {
    this.offset = offset;
  }


  public RelativeBoundary absolute(OffsetDateTime absolute) {
    
    this.absolute = absolute;
    return this;
  }

   /**
   * An explicit absolute instant.
   * @return absolute
  **/
  @jakarta.annotation.Nullable
  public OffsetDateTime getAbsolute() {
    return absolute;
  }


  public void setAbsolute(OffsetDateTime absolute) {
    this.absolute = absolute;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelativeBoundary relativeBoundary = (RelativeBoundary) o;
    return Objects.equals(this.now, relativeBoundary.now) &&
        Objects.equals(this.midnight, relativeBoundary.midnight) &&
        Objects.equals(this.offset, relativeBoundary.offset) &&
        Objects.equals(this.absolute, relativeBoundary.absolute);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(now, midnight, offset, absolute);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelativeBoundary {\n");
    sb.append("    now: ").append(toIndentedString(now)).append("\n");
    sb.append("    midnight: ").append(toIndentedString(midnight)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    absolute: ").append(toIndentedString(absolute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("now");
    openapiFields.add("midnight");
    openapiFields.add("offset");
    openapiFields.add("absolute");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to RelativeBoundary
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RelativeBoundary.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RelativeBoundary is not found in the empty JSON string", RelativeBoundary.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `offset`
      if (jsonObj.get("offset") != null && !jsonObj.get("offset").isJsonNull()) {
        RelativeOffset.validateJsonElement(jsonObj.get("offset"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RelativeBoundary.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RelativeBoundary' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RelativeBoundary> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RelativeBoundary.class));

       return (TypeAdapter<T>) new TypeAdapter<RelativeBoundary>() {
           @Override
           public void write(JsonWriter out, RelativeBoundary value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RelativeBoundary read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RelativeBoundary given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RelativeBoundary
  * @throws IOException if the JSON string is invalid with respect to RelativeBoundary
  */
  public static RelativeBoundary fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RelativeBoundary.class);
  }

 /**
  * Convert an instance of RelativeBoundary to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
