/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.insights.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.insights.JSON;

/**
 * One minute of request activity for a single service and endpoint.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RequestsPerMinuteBucket {
  public static final String SERIALIZED_NAME_MINUTE_BUCKET = "minuteBucket";
  @SerializedName(SERIALIZED_NAME_MINUTE_BUCKET)
  private OffsetDateTime minuteBucket;

  public static final String SERIALIZED_NAME_SERVICE = "service";
  @SerializedName(SERIALIZED_NAME_SERVICE)
  private String service;

  public static final String SERIALIZED_NAME_ENDPOINT = "endpoint";
  @SerializedName(SERIALIZED_NAME_ENDPOINT)
  private String endpoint;

  public static final String SERIALIZED_NAME_TOTAL_REQUESTS = "totalRequests";
  @SerializedName(SERIALIZED_NAME_TOTAL_REQUESTS)
  private Long totalRequests;

  public static final String SERIALIZED_NAME_REQUESTS5XX = "requests5xx";
  @SerializedName(SERIALIZED_NAME_REQUESTS5XX)
  private Long requests5xx;

  public static final String SERIALIZED_NAME_DURATION_SUM_MS = "durationSumMs";
  @SerializedName(SERIALIZED_NAME_DURATION_SUM_MS)
  private java.math.BigDecimal durationSumMs;

  public RequestsPerMinuteBucket() {
  }

  public RequestsPerMinuteBucket minuteBucket(OffsetDateTime minuteBucket) {
    
    this.minuteBucket = minuteBucket;
    return this;
  }

   /**
   * Start of the whole minute this row covers, in UTC.
   * @return minuteBucket
  **/
  @jakarta.annotation.Nonnull
  public OffsetDateTime getMinuteBucket() {
    return minuteBucket;
  }


  public void setMinuteBucket(OffsetDateTime minuteBucket) {
    this.minuteBucket = minuteBucket;
  }


  public RequestsPerMinuteBucket service(String service) {
    
    this.service = service;
    return this;
  }

   /**
   * The name of the service (application) that handled the requests.
   * @return service
  **/
  @jakarta.annotation.Nullable
  public String getService() {
    return service;
  }


  public void setService(String service) {
    this.service = service;
  }


  public RequestsPerMinuteBucket endpoint(String endpoint) {
    
    this.endpoint = endpoint;
    return this;
  }

   /**
   * The endpoint (API operation) the requests were made to.
   * @return endpoint
  **/
  @jakarta.annotation.Nullable
  public String getEndpoint() {
    return endpoint;
  }


  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }


  public RequestsPerMinuteBucket totalRequests(Long totalRequests) {
    
    this.totalRequests = totalRequests;
    return this;
  }

   /**
   * The number of requests in this minute, or null if not reported.
   * @return totalRequests
  **/
  @jakarta.annotation.Nullable
  public Long getTotalRequests() {
    return totalRequests;
  }


  public void setTotalRequests(Long totalRequests) {
    this.totalRequests = totalRequests;
  }


  public RequestsPerMinuteBucket requests5xx(Long requests5xx) {
    
    this.requests5xx = requests5xx;
    return this;
  }

   /**
   * The number of requests in this minute that returned a 5xx status code, or null if not reported.
   * @return requests5xx
  **/
  @jakarta.annotation.Nullable
  public Long getRequests5xx() {
    return requests5xx;
  }


  public void setRequests5xx(Long requests5xx) {
    this.requests5xx = requests5xx;
  }


  public RequestsPerMinuteBucket durationSumMs(java.math.BigDecimal durationSumMs) {
    
    this.durationSumMs = durationSumMs;
    return this;
  }

   /**
   * The sum of the request durations in this minute, in milliseconds, or null if not reported.
   * @return durationSumMs
  **/
  @jakarta.annotation.Nullable
  public java.math.BigDecimal getDurationSumMs() {
    return durationSumMs;
  }


  public void setDurationSumMs(java.math.BigDecimal durationSumMs) {
    this.durationSumMs = durationSumMs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestsPerMinuteBucket requestsPerMinuteBucket = (RequestsPerMinuteBucket) o;
    return Objects.equals(this.minuteBucket, requestsPerMinuteBucket.minuteBucket) &&
        Objects.equals(this.service, requestsPerMinuteBucket.service) &&
        Objects.equals(this.endpoint, requestsPerMinuteBucket.endpoint) &&
        Objects.equals(this.totalRequests, requestsPerMinuteBucket.totalRequests) &&
        Objects.equals(this.requests5xx, requestsPerMinuteBucket.requests5xx) &&
        (this.durationSumMs.compareTo(requestsPerMinuteBucket.getDurationSumMs()) == 0);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(minuteBucket, service, endpoint, totalRequests, requests5xx, durationSumMs);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestsPerMinuteBucket {\n");
    sb.append("    minuteBucket: ").append(toIndentedString(minuteBucket)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    totalRequests: ").append(toIndentedString(totalRequests)).append("\n");
    sb.append("    requests5xx: ").append(toIndentedString(requests5xx)).append("\n");
    sb.append("    durationSumMs: ").append(toIndentedString(durationSumMs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("minuteBucket");
    openapiFields.add("service");
    openapiFields.add("endpoint");
    openapiFields.add("totalRequests");
    openapiFields.add("requests5xx");
    openapiFields.add("durationSumMs");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("minuteBucket");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to RequestsPerMinuteBucket
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RequestsPerMinuteBucket.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RequestsPerMinuteBucket is not found in the empty JSON string", RequestsPerMinuteBucket.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RequestsPerMinuteBucket.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("service") != null && !jsonObj.get("service").isJsonNull()) && !jsonObj.get("service").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `service` to be a primitive type in the JSON string but got `%s`", jsonObj.get("service").toString()));
      }
      if ((jsonObj.get("endpoint") != null && !jsonObj.get("endpoint").isJsonNull()) && !jsonObj.get("endpoint").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endpoint` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endpoint").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RequestsPerMinuteBucket.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RequestsPerMinuteBucket' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RequestsPerMinuteBucket> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RequestsPerMinuteBucket.class));

       return (TypeAdapter<T>) new TypeAdapter<RequestsPerMinuteBucket>() {
           @Override
           public void write(JsonWriter out, RequestsPerMinuteBucket value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RequestsPerMinuteBucket read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RequestsPerMinuteBucket given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RequestsPerMinuteBucket
  * @throws IOException if the JSON string is invalid with respect to RequestsPerMinuteBucket
  */
  public static RequestsPerMinuteBucket fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RequestsPerMinuteBucket.class);
  }

 /**
  * Convert an instance of RequestsPerMinuteBucket to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
