/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.insights.model;

import java.util.Objects;
import com.finbourne.insights.model.ServiceEndpointDuration;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.insights.JSON;

/**
 * Request duration distribution per service and endpoint over a rolling twenty four hour window.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServiceEndpointDurations24hDataSet {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_WINDOW_START = "windowStart";
  @SerializedName(SERIALIZED_NAME_WINDOW_START)
  private OffsetDateTime windowStart;

  public static final String SERIALIZED_NAME_WINDOW_END = "windowEnd";
  @SerializedName(SERIALIZED_NAME_WINDOW_END)
  private OffsetDateTime windowEnd;

  public static final String SERIALIZED_NAME_TRUNCATED = "truncated";
  @SerializedName(SERIALIZED_NAME_TRUNCATED)
  private Boolean truncated;

  public static final String SERIALIZED_NAME_VALUES = "values";
  @SerializedName(SERIALIZED_NAME_VALUES)
  private List<ServiceEndpointDuration> values = new ArrayList<>();

  public ServiceEndpointDurations24hDataSet() {
  }

  public ServiceEndpointDurations24hDataSet name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The name of this data set. Always &#x60;ServiceEndpointDurations24h&#x60;, matching the corresponding Finbourne.Insights.WebApi.Dtos.Metrics.MetricDataSet value and Finbourne.Insights.WebApi.Dtos.Metrics.MetricsResponse property.
   * @return name
  **/
  @jakarta.annotation.Nonnull
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ServiceEndpointDurations24hDataSet windowStart(OffsetDateTime windowStart) {
    
    this.windowStart = windowStart;
    return this;
  }

   /**
   * Inclusive start of the window the data covers, in UTC, floored to a whole minute.
   * @return windowStart
  **/
  @jakarta.annotation.Nonnull
  public OffsetDateTime getWindowStart() {
    return windowStart;
  }


  public void setWindowStart(OffsetDateTime windowStart) {
    this.windowStart = windowStart;
  }


  public ServiceEndpointDurations24hDataSet windowEnd(OffsetDateTime windowEnd) {
    
    this.windowEnd = windowEnd;
    return this;
  }

   /**
   * End of the window the data covers, in UTC, floored to a whole minute.
   * @return windowEnd
  **/
  @jakarta.annotation.Nonnull
  public OffsetDateTime getWindowEnd() {
    return windowEnd;
  }


  public void setWindowEnd(OffsetDateTime windowEnd) {
    this.windowEnd = windowEnd;
  }


  public ServiceEndpointDurations24hDataSet truncated(Boolean truncated) {
    
    this.truncated = truncated;
    return this;
  }

   /**
   * True when the query reached the row cap, so some services or endpoints are missing. False when the whole result set was returned.
   * @return truncated
  **/
  @jakarta.annotation.Nonnull
  public Boolean getTruncated() {
    return truncated;
  }


  public void setTruncated(Boolean truncated) {
    this.truncated = truncated;
  }


  public ServiceEndpointDurations24hDataSet values(List<ServiceEndpointDuration> values) {
    
    this.values = values;
    return this;
  }

  public ServiceEndpointDurations24hDataSet addValuesItem(ServiceEndpointDuration valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<>();
    }
    this.values.add(valuesItem);
    return this;
  }

   /**
   * The rows, ordered by service then endpoint.
   * @return values
  **/
  @jakarta.annotation.Nonnull
  public List<ServiceEndpointDuration> getValues() {
    return values;
  }


  public void setValues(List<ServiceEndpointDuration> values) {
    this.values = values;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceEndpointDurations24hDataSet serviceEndpointDurations24hDataSet = (ServiceEndpointDurations24hDataSet) o;
    return Objects.equals(this.name, serviceEndpointDurations24hDataSet.name) &&
        Objects.equals(this.windowStart, serviceEndpointDurations24hDataSet.windowStart) &&
        Objects.equals(this.windowEnd, serviceEndpointDurations24hDataSet.windowEnd) &&
        Objects.equals(this.truncated, serviceEndpointDurations24hDataSet.truncated) &&
        Objects.equals(this.values, serviceEndpointDurations24hDataSet.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, windowStart, windowEnd, truncated, values);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceEndpointDurations24hDataSet {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    windowStart: ").append(toIndentedString(windowStart)).append("\n");
    sb.append("    windowEnd: ").append(toIndentedString(windowEnd)).append("\n");
    sb.append("    truncated: ").append(toIndentedString(truncated)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("windowStart");
    openapiFields.add("windowEnd");
    openapiFields.add("truncated");
    openapiFields.add("values");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("windowStart");
    openapiRequiredFields.add("windowEnd");
    openapiRequiredFields.add("truncated");
    openapiRequiredFields.add("values");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ServiceEndpointDurations24hDataSet
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceEndpointDurations24hDataSet.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceEndpointDurations24hDataSet is not found in the empty JSON string", ServiceEndpointDurations24hDataSet.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ServiceEndpointDurations24hDataSet.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("values").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `values` to be an array in the JSON string but got `%s`", jsonObj.get("values").toString()));
      }

      JsonArray jsonArrayvalues = jsonObj.getAsJsonArray("values");
      // validate the required field `values` (array)
      for (int i = 0; i < jsonArrayvalues.size(); i++) {
        ServiceEndpointDuration.validateJsonElement(jsonArrayvalues.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceEndpointDurations24hDataSet.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceEndpointDurations24hDataSet' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceEndpointDurations24hDataSet> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceEndpointDurations24hDataSet.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceEndpointDurations24hDataSet>() {
           @Override
           public void write(JsonWriter out, ServiceEndpointDurations24hDataSet value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceEndpointDurations24hDataSet read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ServiceEndpointDurations24hDataSet given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ServiceEndpointDurations24hDataSet
  * @throws IOException if the JSON string is invalid with respect to ServiceEndpointDurations24hDataSet
  */
  public static ServiceEndpointDurations24hDataSet fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceEndpointDurations24hDataSet.class);
  }

 /**
  * Convert an instance of ServiceEndpointDurations24hDataSet to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
