/*
 * FINBOURNE Insights API
 *
 * Contact: info@finbourne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.finbourne.insights.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.finbourne.insights.JSON;

/**
 * Represents an edge connecting two nodes within a trace diagram.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class TraceDiagramEdge {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NODE_ID = "nodeId";
  @SerializedName(SERIALIZED_NAME_NODE_ID)
  private String nodeId;

  public static final String SERIALIZED_NAME_CHILD_NODE_ID = "childNodeId";
  @SerializedName(SERIALIZED_NAME_CHILD_NODE_ID)
  private String childNodeId;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public TraceDiagramEdge() {
  }

  public TraceDiagramEdge id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Sequential identifier of the edge.
   * @return id
  **/
  @jakarta.annotation.Nullable
  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public TraceDiagramEdge nodeId(String nodeId) {
    
    this.nodeId = nodeId;
    return this;
  }

   /**
   * Identifier of the parent node.
   * @return nodeId
  **/
  @jakarta.annotation.Nullable
  public String getNodeId() {
    return nodeId;
  }


  public void setNodeId(String nodeId) {
    this.nodeId = nodeId;
  }


  public TraceDiagramEdge childNodeId(String childNodeId) {
    
    this.childNodeId = childNodeId;
    return this;
  }

   /**
   * Identifier of the child node.
   * @return childNodeId
  **/
  @jakarta.annotation.Nullable
  public String getChildNodeId() {
    return childNodeId;
  }


  public void setChildNodeId(String childNodeId) {
    this.childNodeId = childNodeId;
  }


  public TraceDiagramEdge label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * Label displayed for the edge.
   * @return label
  **/
  @jakarta.annotation.Nullable
  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TraceDiagramEdge traceDiagramEdge = (TraceDiagramEdge) o;
    return Objects.equals(this.id, traceDiagramEdge.id) &&
        Objects.equals(this.nodeId, traceDiagramEdge.nodeId) &&
        Objects.equals(this.childNodeId, traceDiagramEdge.childNodeId) &&
        Objects.equals(this.label, traceDiagramEdge.label);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nodeId, childNodeId, label);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TraceDiagramEdge {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nodeId: ").append(toIndentedString(nodeId)).append("\n");
    sb.append("    childNodeId: ").append(toIndentedString(childNodeId)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("nodeId");
    openapiFields.add("childNodeId");
    openapiFields.add("label");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TraceDiagramEdge
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TraceDiagramEdge.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TraceDiagramEdge is not found in the empty JSON string", TraceDiagramEdge.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("nodeId") != null && !jsonObj.get("nodeId").isJsonNull()) && !jsonObj.get("nodeId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nodeId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nodeId").toString()));
      }
      if ((jsonObj.get("childNodeId") != null && !jsonObj.get("childNodeId").isJsonNull()) && !jsonObj.get("childNodeId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `childNodeId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("childNodeId").toString()));
      }
      if ((jsonObj.get("label") != null && !jsonObj.get("label").isJsonNull()) && !jsonObj.get("label").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `label` to be a primitive type in the JSON string but got `%s`", jsonObj.get("label").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TraceDiagramEdge.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TraceDiagramEdge' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TraceDiagramEdge> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TraceDiagramEdge.class));

       return (TypeAdapter<T>) new TypeAdapter<TraceDiagramEdge>() {
           @Override
           public void write(JsonWriter out, TraceDiagramEdge value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TraceDiagramEdge read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TraceDiagramEdge given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TraceDiagramEdge
  * @throws IOException if the JSON string is invalid with respect to TraceDiagramEdge
  */
  public static TraceDiagramEdge fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TraceDiagramEdge.class);
  }

 /**
  * Convert an instance of TraceDiagramEdge to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}
